### ISSUE TITLE
 Check the validity of the bookmark link to the website

### ISSUE THREAD

**Issue by ilsaul** [sissbruecker/linkding#674] opened 2024-04-01 21:53 UTC
Hi, I looked for this question, basic for me but I couldn't find it. Sorry if I put it back anyway.
I have more than 1500 links over the last 15 years, many of them have been closed.
For me, opening one by one and checking if it exists is a long process. Is it possible to have a system that validates all existing links and if it receives a 404 or other http error adds an error tag to the link?
Another common error is DNS_PROBE_FINISHED_NXDOMAIN when DNS no longer exists.

Thank you

**Comment by sissbruecker** [comment] 2024-04-01 22:08
Seems like a duplicate of https://github.com/sissbruecker/linkding/issues/68. Could you please add your suggestions there?

**Closed by sissbruecker** 2024-04-01 22:08 UTC

**Comment by ilsaul** [comment] 2024-04-01 22:10
thank you.
I didn't find that.
