### ISSUE TITLE
enhancement  Logical operators in tag search for exclude or include multiples tags

### ISSUE THREAD

**Issue by nkgiovannivl** [sissbruecker/linkding#597] opened 2024-01-04 22:23 UTC
Hi! I've just found linkding, great project thanks!

I normal usage some time take me time to found de correct link using tags, would be great search usind logical operators into the tags.

Example:

#local and #web => Search links with #local AND #web tags
#local and !#web => Search links with #local AND NOT #web tags
#local or !#web => Search links with #local OR #web tags
(#local and !#web) or #visual => Search links with #local AND NOT #web tags or any link with #visual tag

**Comment by sissbruecker** [comment] 2024-01-27 15:41
Looks like a dupe of https://github.com/sissbruecker/linkding/issues/93

**Closed by sissbruecker** 2024-01-27 15:41 UTC
