### ISSUE TITLE
Error importing bookmarks

### ISSUE THREAD

**Issue by ericmoon** [sissbruecker/linkding#18] opened 2020-05-04 17:50 UTC
Running in a docker from hub.docker.com:
 sissbruecker/linkding:latest | pulled on 2020-04-07 15:16:52

I can't seem to get the import to work.  I've tried exporting from Firefox and Chrome, but always the same error:
An error occurred during bookmark import.

Any pointers to enabling error logs on the docker instance?  If I was running the dev setup, I would enable the debug logs in django settings, but want to avoid that, if possible and keep it within docker.

**Comment by sissbruecker** [comment] 2020-05-04 18:50
Hey @ericmoon , thanks for the report, I'll try to reproduce when I find some time.

As for logging, I just looked at the code and it looks like the error is caught but not logged 😬. So that would have to be improved as well.

**Comment by arpitgogia** [comment] 2020-06-06 18:11
Hey @sissbruecker I was able to narrow down the issue to `KeyError` being raised while importing bookmarks, because of the absence of certain attributes in the tag.

I have opened #20 that addresses this

**Comment by sissbruecker** [comment] 2020-06-07 13:13
The root cause should be fixed thanks to @arpitgogia . I also added some error handling and logging around the importer. I updated the Docker image with the fixes.

I'll close this for now, please reopen if the issue persists.

**Closed by sissbruecker** 2020-06-07 13:13 UTC
