### ISSUE TITLE
 importing bookmarks in this format ，folder information will be lost, resulting in chaos

### ISSUE THREAD

**Issue by zhenruyan** [sissbruecker/linkding#586] opened 2023-12-04 10:35 UTC
I haven't received a similar issue request, but it supports importing bookmark files in directory format

---- github save
\\--  golang.com
\\ --  xxxx.com
\\--  doc.com
---- host
\\--  vhost.com
\\--  phphost.com

When importing bookmarks in this format, folder information will be lost, resulting in chaos

**Comment by sissbruecker** [comment] 2024-01-27 16:57
Seems like a dupe of https://github.com/sissbruecker/linkding/issues/69, there are some workarounds mentioned there.

**Closed by sissbruecker** 2024-01-27 16:57 UTC
