### ISSUE TITLE
Feature Request: Bulk link import

### ISSUE THREAD

**Issue by FunctionDJ** [sissbruecker/linkding#301] opened 2022-07-17 20:15 UTC
I often want to dump all my currently opened links into linkding.
I know linkding has a bookmarks import, but only for formatted HTML files, i.e. bookmark exports.

It's not possible to obtain all links of a window by using a bookmarklet, but it's possible with a browser extension.
A change to the browser extension is not necessary though because the extension [OneTab](https://www.one-tab.com/) can also save and close all URLs of a browser window.
From OneTab, groups of links can be exported in this format (one link per line): `[url] | [browser title]`

Some example output:
```
https://docs.linuxserver.io/general/containers-101 | Docker Containers: 101 - LinuxServer.io
https://www.linuxserver.io/blog/blocking-malicious-connections-with-crowdsec-and-swag | Blocking Malicious Connections With CrowdSec and SWAG | LinuxServer.io
https://hub.docker.com/r/linuxserver/swag | linuxserver/swag - Docker Image | Docker Hub
```

If linkding could parse this output through the web interface it would already make bulk importing easily possible.
I'll happily help with the frontend development part of this feature, but i can't help with the python backend.

**Comment by FunctionDJ** [comment] 2022-07-17 20:16
Also i'd like to note that this feature appears to be missing from every project similar to linkding [based on my comparisons and research](https://gist.github.com/FunctionDJ/ccd23e050ea616a7f6d79ee2cc1fda6f)

**Comment by gil** [comment] 2022-08-10 10:02
Duplicate of #186 ? Or similar, at least.

**Comment by sissbruecker** [comment] 2022-08-13 08:20
> Duplicate of #186 ? Or similar, at least.

Yeah, it's also a bit unfortunate that both tickets request a bulk import feature, when the actual use case is to save all open browser tabs.

I'll close this issue in favor of #186, which would be about importing a text file with links in *some* format. If the actual use-case is to save all open browser tabs, then I would suggest to open an issue for the browser extension in the respective repo.

**Closed by sissbruecker** 2022-08-13 08:20 UTC
