### ISSUE TITLE
Docker container high ram usage

### ISSUE THREAD

**Issue by GreatVoid29A** [sissbruecker/linkding#591] opened 2023-12-15 11:12 UTC
# Docker Container High RAM Usage

## Issue Description

The current Docker container is exhibiting high RAM usage, consuming 8GB of RAM upon a clean start.

```bash
559a56af7ba4   linkding   0.01%     8.108GiB / 62.72GiB   12.93%    1.99kB / 0B   827kB / 0B   8
```

```bash
linkding  | Operations to perform:
linkding  |   Apply all migrations: admin, auth, authtoken, background_task, bookmarks, contenttypes, sessions
linkding  | Running migrations:
linkding  |   Applying contenttypes.0001_initial... OK
linkding  |   Applying auth.0001_initial... OK
linkding  |   Applying admin.0001_initial... OK
linkding  |   Applying admin.0002_logentry_remove_auto_add... OK
linkding  |   Applying admin.0003_logentry_add_action_flag_choices... OK
linkding  |   Applying contenttypes.0002_remove_content_type_name... OK
linkding  |   Applying auth.0002_alter_permission_name_max_length... OK
linkding  |   Applying auth.0003_alter_user_email_max_length... OK
linkding  |   Applying auth.0004_alter_user_username_opts... OK
linkding  |   Applying auth.0005_alter_user_last_login_null... OK
linkding  |   Applying auth.0006_require_contenttypes_0002... OK
linkding  |   Applying auth.0007_alter_validators_add_error_messages... OK
linkding  |   Applying auth.0008_alter_user_username_max_length... OK
linkding  |   Applying auth.0009_alter_user_last_name_max_length... OK
linkding  |   Applying auth.0010_alter_group_name_max_length... OK
linkding  |   Applying auth.0011_update_proxy_permissions... OK
linkding  |   Applying auth.0012_alter_user_first_name_max_length... OK
linkding  |   Applying authtoken.0001_initial... OK
linkding  |   Applying authtoken.0002_auto_20160226_1747... OK
linkding  |   Applying authtoken.0003_tokenproxy... OK
linkding  |   Applying background_task.0001_initial... OK
linkding  |   Applying background_task.0002_auto_20170927_1109... OK
linkding  |   Applying background_task.0003_auto_20210410_1529... OK
linkding  |   Applying background_task.0004_auto_20220202_1721... OK
linkding  |   Applying bookmarks.0001_initial... OK
linkding  |   Applying bookmarks.0002_auto_20190629_2303... OK
linkding  |   Applying bookmarks.0003_auto_20200913_0656... OK
linkding  |   Applying bookmarks.0004_auto_20200926_1028... OK
linkding  |   Applying bookmarks.0005_auto_20210103_1212... OK
linkding  |   Applying bookmarks.0006_bookmark_is_archived... OK
linkding  |   Applying bookmarks.0007_userprofile... OK
linkding  |   Applying bookmarks.0008_userprofile_bookmark_date_display... OK
linkding  |   Applying bookmarks.0009_bookmark_web_archive_snapshot_url... OK
linkding  |   Applying bookmarks.0010_userprofile_bookmark_link_target... OK
linkding  |   Applying bookmarks.0011_userprofile_web_archive_integration... OK
linkding  |   Applying bookmarks.0012_toast... OK
linkding  |   Applying bookmarks.0013_web_archive_optin_toast... OK
linkding  |   Applying bookmarks.0014_alter_bookmark_unread... OK
linkding  |   Applying bookmarks.0015_feedtoken... OK
linkding  |   Applying bookmarks.0016_bookmark_shared... OK
linkding  |   Applying bookmarks.0017_userprofile_enable_sharing... OK
linkding  |   Applying bookmarks.0018_bookmark_favicon_file... OK
linkding  |   Applying bookmarks.0019_userprofile_enable_favicons... OK
linkding  |   Applying bookmarks.0020_userprofile_tag_search... OK
linkding  |   Applying bookmarks.0021_userprofile_display_url... OK
linkding  |   Applying bookmarks.0022_bookmark_notes... OK
linkding  |   Applying bookmarks.0023_userprofile_permanent_notes... OK
linkding  |   Applying sessions.0001_initial... OK
linkding  | 2023-12-15 11:04:55,160 INFO Current journal mode: delete
linkding  | 2023-12-15 11:04:55,163 INFO Switched to WAL journal mode
linkding  | There is already a secret key in `secretkey.txt`
linkding  | 2023-12-15 11:04:55,856 INFO Skip creating initial superuser, LD_SUPERUSER_NAME option is not defined
linkding  | [uWSGI] getting INI configuration from uwsgi.ini
linkding  | [uwsgi-static] added mapping for /static => static
linkding  | [uwsgi-static] added mapping for /static => data/favicons
linkding  | *** Starting uWSGI 2.0.20 (64bit) on [Fri Dec 15 13:04:55 2023] ***
linkding  | compiled with version: 8.3.0 on 29 July 2023 09:26:19
linkding  | os: Linux-6.6.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:20 +0000
linkding  | nodename: 559a56af7ba4
linkding  | machine: x86_64
linkding  | clock source: unix
linkding  | detected number of CPU cores: 12
linkding  | current working directory: /etc/linkding
linkding  | writing pidfile to /tmp/linkding.pid
linkding  | detected binary path: /opt/venv/bin/uwsgi
linkding  | !!! no internal routing support, rebuild with pcre support !!!
linkding  | setgid() to 33
linkding  | setuid() to 33
linkding  | your memory page size is 4096 bytes
linkding  | detected max file descriptor number: 1073741816
linkding  | building mime-types dictionary from file /etc/mime.types...565 entry found
linkding  | lock engine: pthread robust mutexes
linkding  | thunder lock: disabled (you can enable it with --thunder-lock)
linkding  | uWSGI http bound on :9090 fd 4
linkding  | uwsgi socket 0 bound to TCP address 127.0.0.1:39617 (port auto-assigned) fd 3
linkding  | Python version: 3.10.6 (main, Aug 23 2022, 08:58:52) [GCC 8.3.0]
linkding  | Python main interpreter initialized at 0x557505fb6a00
linkding  | python threads support enabled
linkding  | your server socket listen backlog is limited to 100 connections
linkding  | your mercy for graceful operations on workers is 60 seconds
linkding  | mapped 274608 bytes (268 KB) for 4 cores
linkding  | *** Operational MODE: preforking+threaded ***
linkding  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x557505fb6a00 pid: 1 (default app)
linkding  | *** uWSGI is running in multiple interpreter mode ***
linkding  | spawned uWSGI master process (pid: 1)
linkding  | spawned uWSGI worker 1 (pid: 16, cores: 2)
linkding  | spawned uWSGI worker 2 (pid: 18, cores: 2)
linkding  | *** Stats server enabled on 127.0.0.1:9191 fd: 14 ***
linkding  | spawned uWSGI http 1 (pid: 20)
```

**Comment by rmszc81** [comment] 2023-12-15 18:13
@GreatVoid29A I'm also having problems in my rasbperry pi 4 model b with 8gb of ram:

```
malloc(): Out of memory [core/utils.c line 1801]
!!! tried memory allocation of 8589934528 bytes !!!
respawned uWSGI http 1 (pid: 353)
```

in my case linkding never goes up, the container is kept into a zombie state.

@sissbruecker any idea?

thanks a lot and have a nice weekend!

**Comment by sissbruecker** [comment] 2023-12-15 18:18
This is a dupe of https://github.com/sissbruecker/linkding/issues/453, check the thread there for a workaround.

**Closed by sissbruecker** 2023-12-15 18:18 UTC
