### ISSUE TITLE
Cyrillic search is case sensetive

### ISSUE THREAD

**Issue by ostapblender1** [sissbruecker/linkding#485] opened 2023-06-05 07:54 UTC
Search request containing cyrillic symbols become case sensetive. In russian or ukranian or even kazakh language searching substrings "Почта" and "почта" returns different result.

**Comment by sissbruecker** [comment] 2023-06-05 09:02
Duplicate of https://github.com/sissbruecker/linkding/issues/181

**Closed by sissbruecker** 2023-06-05 09:02 UTC
