### ISSUE TITLE
Add Automated, periodic link validation

### ISSUE THREAD

**Issue by inspector71** [sissbruecker/linkding#117] opened 2021-04-24 05:23 UTC
Looking for a similar app to yours that does the one thing I feel a bookmarking tool really needs: automated link validation. Transient nature of the web can be improved by archiving but for non-archived links, scheduled background validation to weed out misbehaving links seems logical.

Regardless, thanks for publishing your code and all the hard work that went into it.

**Comment by sissbruecker** [comment] 2021-05-13 17:15
This feature doesn't exist ATM, but it would be useful. If you are considering alternative tools you might want to check out https://github.com/Kovah/LinkAce/

Personally I agree in theory that this would be useful but in practice I don't find that this is a big issue. I notice that I tend to access older bookmarks less and less. If something really is offline by then, well bad luck, but no big deal. I'll just remove it. Again, just my personal observation.

**Comment by sissbruecker** [comment] 2021-05-13 17:16
Also closing this as a duplicate of #68

**Closed by sissbruecker** 2021-05-13 17:16 UTC
Labels: enhancement
