### ISSUE TITLE
Add PWA support to use "Share with..." on Android

### ISSUE THREAD

**Issue by edersong** [sissbruecker/linkding#558] opened 2023-10-16 16:32 UTC
Add PWA support to use "Share with..." on Android to save bookmarks to a "Read it later" tag

**Comment by sokai** [comment] 2023-12-09 22:41
FYI @edersong: https://github.com/linka-app/linka seems interesting

**Comment by dahamsta** [comment] 2024-01-23 17:05
Just want to bump this, for PWA support in general.

**Comment by sissbruecker** [comment] 2024-01-27 17:20
Dupe of #98

**Closed by sissbruecker** 2024-01-27 17:20 UTC

**Comment by danielyrovas** [comment] 2024-02-16 00:23
Hey @edersong, are you interested in testing an Android app? I have written a small unofficial client for LinkDing [here](https://github.com/danielyrovas/linklater). It can add tags to bookmarks when you save them.
You can install it directly from the releases or using [Obtainium](https://github.com/ImranR98/Obtainium).

**Comment by karlhorky** [comment] 2026-03-08 11:13
The web-share-target PWA API has been implemented in v1.25.0 (Mar 2024), so IIUC "Share with..." should work with a PWA on Android now:

- https://github.com/sissbruecker/linkding/pull/630
- https://github.com/sissbruecker/linkding/releases/tag/v1.25.0

Otherwise, there appears to be a Flutter app called Linkdy from @JGeek00 which is available in the Play Store:

- https://github.com/JGeek00/linkdy
