### ISSUE TITLE
Not Acceptable! on WordPress Sites

### ISSUE THREAD

**Issue by zahidhanif** [sissbruecker/linkding#116] opened 2021-04-20 14:20 UTC
Firstly, thanks for the great app. I am self-hosting and slowly moving my bookmarks over. When I add a bookmark using the Chrome extension, many WordPress sites are recording "Not Acceptable!" for the website title. When looking at the HTML page title, I am guessing it does not like the "&#8211;" (dash) in the title.

**Comment by sissbruecker** [comment] 2021-05-13 17:21
This seems to be caused by a Wordpress plugin that tries to secure the website against unwanted requests, e.g. from spammers or bots.

Linkding does its website scraping on the server-side and not from the browser. That can lead to websites thinking that linkding is a bot for example, because the request does not come from a browser. See also discussion in #118 

I'll close this in favor of #118 as that has more technical background on the issue. Please follow that one on updates.

**Comment by sissbruecker** [comment] 2021-05-13 17:21
Forgot to add: See here for reference on the wordpress plugin: https://bobcares.com/blog/406-not-acceptable-wordpress/

**Closed by sissbruecker** 2021-05-13 17:21 UTC
