### ISSUE TITLE
[Feature Request] Link Checker

### ISSUE THREAD

**Issue by stonesbg** [sissbruecker/linkding#526] opened 2023-09-06 21:07 UTC
It would be a nice feature if there was a link checker that could scan all of the bookmarks and then based on the results create tags agains the urls.

That way you can find dead links vs active links.  From there potentially archive or grab a backup from wayback machine

**Comment by sissbruecker** [comment] 2023-09-07 10:18
Duplicate of https://github.com/sissbruecker/linkding/issues/68

**Closed by sissbruecker** 2023-09-07 10:18 UTC
