### ISSUE TITLE
Unable to create bookmark for local urls

### ISSUE THREAD

**Issue by theperiscope** [sissbruecker/linkding#461] opened 2023-04-29 01:45 UTC
Running 1.17.2 version, I get _Enter a valid URL._ error for the following scenarios:

1. https://d1/
2. https://d1:8888/

When domain suffix such as '.local' is used, issue does not occur and bookmark is added successfully.

**Comment by sissbruecker** [comment] 2023-05-02 08:00
Closing as duplicate of https://github.com/sissbruecker/linkding/issues/206, as the underlying root issue is how the Django URL validator is implemented.

**Closed by sissbruecker** 2023-05-02 08:00 UTC
