### ISSUE TITLE
Feature Request: Add Option to enable/disable automatic description when adding a bookmark

### ISSUE THREAD

**Issue by dxnxz** [sissbruecker/linkding#760] opened 2024-06-17 13:46 UTC
Hi there!

Thanks for your great work. I noticed something:
- open the dialogue to add a bookmark
- paste the link -> description is prefilled
- click the edit button next to description
- remove the text from the textbox
- save the bookmark
- description is still saved

If that is by design, would it be possible to add an option to toggle the automatic description?

Best, 
Deniz

**Comment by sissbruecker** [comment] 2024-08-28 22:03
Duplicate of https://github.com/sissbruecker/linkding/issues/15

**Closed by sissbruecker** 2024-08-28 22:03 UTC
