### ISSUE TITLE
Tag clicking sometimes does not work 

### ISSUE THREAD

**Issue by aashish108** [sissbruecker/linkding#238] opened 2022-04-01 07:00 UTC
When I click on a tag, I see articles and all the tags that the articles listed have, like x, x.1. If I click x tag, I would have thought that I would see all articles that are tagged with x but, instead, what happens is that the tag name gets appended to the search box and nothing seems to happen!

Looks like a bug?

**Comment by sissbruecker** [comment] 2022-05-13 23:45
I can not quite follow your description. In your first sentence you mention that the feature works, in the second sentence you mention that it doesn't. Can you please clarify the steps, and maybe provide a reproduction (e.g. database, bookmark export).?

**Comment by aashish108** [comment] 2022-05-14 08:25
First state
![image](https://user-images.githubusercontent.com/7046226/168417570-f9fb1f7a-9750-4b50-ae99-9a3e7692d320.png)

I want to click Shopping.cars to see the items from that tag only:
![image](https://user-images.githubusercontent.com/7046226/168417597-6d9ecd33-95ad-47fb-a39f-43a3b91886bf.png)

But all that happens is that the tag gets appended to whats there in the search box. I would have thought that clicking a tag will take me to all articles related to that tag? So what I usually have to do is to manually edit the search box. Just one issue I came across.

**Comment by sissbruecker** [comment] 2022-05-14 08:57
OK I get it. Yeah, that is intended. The idea is that you can narrow down your search by gradually adding more tags. For example, you select some tag and then get like 200 bookmarks. As that is too much, you click on a second tag, and the search result gets narrowed down to a combination of both tags, resulting in let's say 10 bookmarks.

What you want is to replace the searched tag, or probably the whole search string, which doesn't necessary only contain a single tag, with a different one.

**Comment by aashish108** [comment] 2022-05-14 10:11
> OK I get it. Yeah, that is intended. The idea is that you can narrow down your search by gradually adding more tags. For example, you select some tag and then get like 200 bookmarks. As that is too much, you click on a second tag, and the search result gets narrowed down to a combination of both tags, resulting in let's say 10 bookmarks.
> 
> What you want is to replace the searched tag, or probably the whole search string, which doesn't necessary only contain a single tag, with a different one.

OK I understand! One thing if you keep clicking the tag it keeps appending, why not if you click twice it will exclusively search that tag rather than adding a duplicate tag? Also I don't see narrowing down working after the 2nd narrow unless you over tag your stuff and have a third level tag planned out!

**Comment by sissbruecker** [comment] 2022-08-04 19:30
With #307 selected tags are now displayed in the tag cloud, and can be removed by clicking on them. I'm going to close this for now. An idea for the future could be to add a mode where clicking a tag does replace existing tags in the query.

**Closed by sissbruecker** 2022-08-04 19:30 UTC
Labels: question
