### ISSUE TITLE
when a tag is clicked and it's already in search

### ISSUE THREAD

**Issue by gingerbeardman** [sissbruecker/linkding#209] opened 2022-02-22 22:06 UTC
1. click a tag to filter by that
2. click the same tag again

What happens
- the tag appears twice in the search filter

Expected
- tag should be removed from search

or, at least
- tag should not appear twice

**Comment by sissbruecker** [comment] 2022-05-14 01:05
Duplicate of https://github.com/sissbruecker/linkding/issues/111

**Closed by sissbruecker** 2022-05-14 01:05 UTC
Labels: enhancement
