### ISSUE TITLE
Dead link checker

### ISSUE THREAD

**Issue by dahamsta** [sissbruecker/linkding#324] opened 2022-08-15 20:03 UTC
Would it be possible to add a dead link checker? That is, a function to run through the links and output links that aren't 200 ok, with an option to delete, and perhaps replace with Wayback, etc? Or perhaps run on a schedule and send a report? Or both? :)

Apologies if this is a dupe request, I did search but wasn't sure about keywords.

**Comment by sissbruecker** [comment] 2022-08-15 20:18
Yeah, this is a duplicate of https://github.com/sissbruecker/linkding/issues/68. You can comment there if you like.

**Closed by sissbruecker** 2022-08-15 20:18 UTC
