### ISSUE TITLE
So many Queued tasks

### ISSUE THREAD

**Issue by Drallas** [sissbruecker/linkding#771] opened 2024-06-29 08:27 UTC
Discovered this wonderful Bookmark manager, and we are all in! 😄 

Only noticed an enormous amount of Queued tasks in the Admin Panel, why is that?

<img width="1392" alt="Screenshot 2024-06-29 at 10 24 27" src="https://github.com/sissbruecker/linkding/assets/24792888/0182aed1-ea7f-47ed-8ebe-cc6f3bdaa2a4">

**Comment by BadCo-NZ** [comment] 2024-07-07 01:15
Are they not the tasks for saving offline copies of websites added to linkding?

**Comment by sissbruecker** [comment] 2024-08-28 21:40
You've probably enabled the Internet Archive integration and then imported several thousand bookmarks. Now it's trying to load snapshots for all imported bookmarks. 

There has been some kind of regression recently where the API that linkding uses has a more strict rate limit now, which means lots of tasks will fail and then stay queued due to using an exponential backoff. Would make sense to replace the API usage with just generating a static link to the and hoping that a snapshot exists for that.

**Comment by sissbruecker** [comment] 2024-08-28 22:01
Closing as a duplicate of https://github.com/sissbruecker/linkding/issues/747

**Closed by sissbruecker** 2024-08-28 22:01 UTC
Labels: bug
