### ISSUE TITLE
Errors when importing many bookmarks (Server Errors 500, 405 and more)

### ISSUE THREAD

**Issue by gingerbeardman** [sissbruecker/linkding#202] opened 2022-02-22 12:42 UTC
Hi,

Thanks for this project!

I just set it up using docker and imported my ~4100 bookmarks from Pinboard.

- On import there was no success message, clicking the linkding logo to get away from that page resulted in server error 500.
- Clicking a tag resulted in a server error 500, clicking the same tag again now there is no error

Attached is a log from the docker container that shows the 500 errors.

Can I find out any information to help you diagnose/solve?

[linkding.csv](https://github.com/sissbruecker/linkding/files/8116658/linkding.csv)

**Comment by sissbruecker** [comment] 2022-02-22 12:55
The import is definitely not very fast, and importing such a large number of bookmarks usually takes a while. According to the logs it seems you navigated to the homepage 10secs after starting the import, that seems too fast to import that amount of bookmarks.

> On import there was no success message

Unfortunately there is no visual feedback while the import is running, but you can take a look at whether your browser is showing a loading indicator. After the import finishes, it should reload the page and display a message below the file upload field:

![Bildschirmfoto 2022-02-22 um 13 46 45](https://user-images.githubusercontent.com/357820/155135241-dcf40fd8-9528-44e6-8e54-6e06547addfa.png)

The errors kind of sound like the import was not completed, though I can't explain why that would result in the behavior you described. I would suggest to run the import and wait until you see the message above. If you are running into timeouts, take a look at [this option](https://github.com/sissbruecker/linkding/blob/master/docs/Options.md#ld_request_timeout) and see if it improves things.

**Comment by gingerbeardman** [comment] 2022-02-22 13:26
Intersting! For comparison Shaarli imported ~@4700 almost instantly, a second or two.

I guess I need to check if all my bookmarks have imported. Is there anywhere i can see the total number of bookmarks?

Ah, 6 pages of 30 bookmarks means only 180 imported in 10 seconds!?

Hmm. So over 4 minutes to import all my bookmarks... 😧

**Comment by gingerbeardman** [comment] 2022-02-22 13:27
Q: if I do the import again will it overwrite all the bookmarks that have already been imported?

**Comment by gingerbeardman** [comment] 2022-02-22 13:40
Excellent, I'll try again now.

Thanks for the _quick_ support!

**Comment by gingerbeardman** [comment] 2022-02-22 13:47
Doing a new import and waiting: Error 405 not allowed

Trying to get to admin: Error 500

:/

**Comment by gingerbeardman** [comment] 2022-02-22 13:51
I have increased `LD_REQUEST_TIMEOUT` to 300 (5 minutes) fingers crossed for third time lucky

**Comment by gingerbeardman** [comment] 2022-02-22 13:57
It only imports about ~200 bookmarks each try.

4700 means I will have to do import 24 times.

I think I'll give up for today.

**Comment by gingerbeardman** [comment] 2022-02-22 14:12
In console I'm seeing `django.db.utils.OperationalError: database is locked     `

Currently up to 1800 bookmarks, but to be honest I worry about the integrity of the import so far.

**Comment by gingerbeardman** [comment] 2022-02-22 14:16
I've deleted the database and started again.

**Comment by gingerbeardman** [comment] 2022-02-22 14:22
OK, no change. Giving up.

Please keep me informed if there are improvements to the import process. Many thanks.

**Comment by gingerbeardman** [comment] 2022-02-22 14:32
If you'd like me to send you my bookmarks file privately, I'm happy to do so. 

I'll strip the private links from it before hand.

**Comment by gingerbeardman** [comment] 2022-02-22 15:54
I went away to do other stuff and thought I'd check on things... 4166 bookmarks currently imported.

So it seems the import has continued even with the 500/405/database/etc errors.

Pinboard listed 4170 bookmarks so perhaps it's complete?

How bizarre.

**Comment by gingerbeardman** [comment] 2022-02-22 16:54
Importing a file containing only those gives:

> 1 bookmarks were successfully imported.
> 
> 3 bookmarks could not be imported. Please check the logs for more details.

Linkding classes the top three, above, as invalid URLs.

**Comment by sissbruecker** [comment] 2022-05-14 00:52
Bit confusing to follow all of that, so the problem is solved now apart from the validation of the bookmark URLs?

**Comment by gingerbeardman** [comment] 2022-05-15 15:09
Well, there are error messages but they seem to not stop the import. It will proceed with import.

Solved? I guess, but there is room for improvement of user experience.

**Comment by sissbruecker** [comment] 2022-08-13 08:33
I think the issue here was using the app while the import was running, plus the import errors around URL validation. URL validation is covered by another ticket, and the import has become a lot faster which makes it less likely for the user to click around. Closing.

**Closed by sissbruecker** 2022-08-13 08:33 UTC
Labels: question
