### ISSUE TITLE
[Feature request] Better readability of tag cloud with lots of tags

### ISSUE THREAD

**Issue by thany** [sissbruecker/linkding#594] opened 2023-12-28 19:11 UTC
So I have hundreds of tags accumulated over the years. Currently, linkding is just plonking down every tag in the database in alphabetical order, and I'm sure this is perfectly acceptable if you have less than a couple dozen tags. When you got hundreds, the tag list is just no longer useful. Here's but a small part of what it looks like for me:
![image](https://github.com/sissbruecker/linkding/assets/152227/fb4bf0ac-7c61-4c69-913d-0da51b577660)

So I was thnking maybe introduce a "tag cloud" kind of feature where commonly used tags are printed in a bigger font. Or how about ordering tags by usage? Or by date of associated bookmarks? I'm not sure what the best option is, but I do know that this, in my situation at least, is not super useful other than to remind me I should probably cleanup (which, knowing myself, I will postpone indefinitely) 😀

Any (other) ideas for a better UI here?

Edit: Pinboard has "bundles", and Delicious had "tag groups". But that requires manual labour, and is not a solution to the massive wall of tags 🙂

**Comment by ecogit** [comment] 2024-01-07 15:19
Such a graphical output would be a welcome addition. 

And in a second version it would be great to have the ability to filter out specific tags or text patterns, such as meta tags used for internal management (e.g. `archive:tagname-XY`).

**Comment by sissbruecker** [comment] 2024-01-27 16:36
I see your problem, with that amount of tags there probably isn't any meaningful way to display them all at once. Not sure about the proposed solutions. Instead of showing all tags just somewhat differently, I think the best solution would be one where you don't show that many tags in the first place. From my experience most tags are useless, especially the ones only assigned once or twice.

A solution could be to only show tags that have been used (as in: assigned to a bookmark) more than X times, where X is a threshold configurable somewhere. Then have an option to show all at once if you really want to dig through all of those manually to find something. Allowing to define a filter like suggested by ecogit is also interesting, though that seems less valuable as it requires a structured approach to tag naming, which most people probably don't use.

Another suggestion regarding to categorization was to allow manual grouping of tags (https://github.com/sissbruecker/linkding/issues/285#issuecomment-1213905426) so that you at least have distinct categories of tags to look through, though that of course requires manual effort.

**Comment by sissbruecker** [comment] 2024-01-27 17:01
Actually seems like duplicate of #205 , feel free to add your concerns there.

**Closed by sissbruecker** 2024-01-27 17:01 UTC
Labels: enhancement
