### ISSUE TITLE
too many logs 

### ISSUE THREAD

**Issue by Yumega** [sissbruecker/linkding#813] opened 2024-09-01 15:36 UTC
How to hide the logs? only keep the warning or error logs 

![hi_35-45](https://github.com/user-attachments/assets/2269a30a-5df8-414b-a1d7-b064a2a28454)

**Comment by sissbruecker** [comment] 2024-09-08 21:02
Dupe of https://github.com/sissbruecker/linkding/issues/785

**Closed by sissbruecker** 2024-09-08 21:02 UTC
