### ISSUE TITLE
Error importing url with underscore

### ISSUE THREAD

**Issue by Haze-sh** [sissbruecker/linkding#386] opened 2023-01-04 07:05 UTC
URLs that contain an underscore cannot be imported and treated as an invalid url
Example: https://dcz_self.gitlab.io

**Comment by sissbruecker** [comment] 2023-01-06 18:42
Should be a duplicate of https://github.com/sissbruecker/linkding/issues/206

**Closed by sissbruecker** 2023-01-06 18:42 UTC
